[PHP]
date.timezone = Asia/Jakarta
memory_limit = 256M
max_execution_time = 60
post_max_size = 12M
upload_max_filesize = 10M

[opcache]
opcache.enable = 1
opcache.enable_cli = 0
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

